# Generated by Django 4.2.4 on 2023-10-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedbacks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата и время"),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="Электронная почта"),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="message",
            field=models.TextField(verbose_name="Сообщение"),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Имя"),
        ),
    ]
