# Generated by Django 4.2.4 on 2023-10-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedbacks", "0002_alter_feedback_created_at_alter_feedback_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="is_processed",
            field=models.BooleanField(default=False, verbose_name="Обработан"),
        ),
    ]
