# Generated by Django 4.2.4 on 2023-10-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_good_category_alter_good_manufacturer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='good',
            options={'ordering': ('name',), 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.RemoveField(
            model_name='good',
            name='archived',
        ),
        migrations.AddField(
            model_name='good',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активный'),
        ),
    ]
