# Generated by Django 4.2.4 on 2023-10-05 06:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0003_alter_good_options_remove_good_archived_good_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ("name",),
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.AlterModelOptions(
            name="manufacturer",
            options={
                "ordering": ("name",),
                "verbose_name": "Производитель",
                "verbose_name_plural": "Производители",
            },
        ),
    ]
