# Generated by Django 4.2.4 on 2023-10-05 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("goods", "0004_alter_category_options_alter_manufacturer_options"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="OrderItem",
            new_name="OrderGood",
        ),
        migrations.CreateModel(
            name="UserShoppingCart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="Количество")),
                (
                    "good",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shopping_carts",
                        to="goods.good",
                        verbose_name="Товар",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар в корзине",
                "verbose_name_plural": "Корзины",
            },
        ),
        migrations.AddField(
            model_name="good",
            name="is_in_shopping_cart",
            field=models.ManyToManyField(
                related_name="shopping_cart",
                through="goods.UserShoppingCart",
                to=settings.AUTH_USER_MODEL,
                verbose_name="В корзине",
            ),
        ),
        migrations.AddConstraint(
            model_name="usershoppingcart",
            constraint=models.UniqueConstraint(
                fields=("user", "good"), name="already_in_shopping_cart"
            ),
        ),
    ]
