# Generated by Django 4.2.4 on 2023-10-05 08:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0005_rename_orderitem_ordergood_usershoppingcart_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ordergood",
            name="good",
        ),
        migrations.RemoveField(
            model_name="ordergood",
            name="order",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="OrderGood",
        ),
    ]
