# Generated by Django 4.2.4 on 2023-10-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0006_remove_ordergood_good_remove_ordergood_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usershoppingcart",
            name="quantity",
            field=models.PositiveIntegerField(default=1, verbose_name="Количество"),
        ),
    ]
