# Generated by Django 4.2.4 on 2023-10-06 07:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0007_alter_usershoppingcart_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="good",
            name="volume",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Объем, л",
            ),
        ),
    ]
