# Generated by Django 4.2.4 on 2023-10-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0009_alter_good_volume"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                default="sparkling_wine", unique=True, verbose_name="Слаг"
            ),
        ),
    ]
