# Generated by Django 4.2.4 on 2023-10-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0010_category_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(unique=True, verbose_name="Слаг"),
        ),
    ]
