# Generated by Django 4.2.4 on 2023-10-06 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0011_alter_category_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="manufacturer",
            name="slug",
            field=models.SlugField(default="LVMH", unique=True, verbose_name="Слаг"),
        ),
    ]
