# Generated by Django 4.2.4 on 2023-10-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0013_alter_manufacturer_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="manufacturer",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
    ]
