# Generated by Django 4.2.4 on 2023-10-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0014_manufacturer_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='purchase_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Число проданных товаров'),
        ),
    ]
