# Generated by Django 4.2.4 on 2023-10-10 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0015_good_purchase_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="good",
            name="volume",
            field=models.DecimalField(
                decimal_places=3, max_digits=6, verbose_name="Объем, л"
            ),
        ),
    ]
