# Generated by Django 4.2.4 on 2023-10-19 18:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0017_alter_good_category_alter_good_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='usershoppingcart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата добавления'),
            preserve_default=False,
        ),
    ]
