# Generated by Django 4.2.4 on 2023-10-19 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0018_usershoppingcart_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usershoppingcart',
            options={'ordering': ('-created_at',), 'verbose_name': 'Товар в корзине', 'verbose_name_plural': 'Корзины'},
        ),
    ]
