# Generated by Django 4.2.4 on 2023-10-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
            },
        ),
        migrations.AlterModelOptions(
            name="ordergood",
            options={
                "verbose_name": "Товар в заказе",
                "verbose_name_plural": "Товары в заказах",
            },
        ),
        migrations.AlterField(
            model_name="ordergood",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Цена, 1 шт."
            ),
        ),
    ]
