# Generated by Django 4.2.4 on 2023-10-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_alter_order_options_alter_ordergood_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ("id",),
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
            },
        ),
        migrations.AddField(
            model_name="order",
            name="is_delivered",
            field=models.BooleanField(default=False, verbose_name="Доставлен"),
        ),
    ]
