# Generated by Django 4.2.4 on 2023-10-05 09:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_alter_order_options_order_is_delivered"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="total_price",
        ),
    ]
