# Generated by Django 4.2.4 on 2023-10-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_remove_order_total_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.TextField(max_length=1000, verbose_name="Адрес"),
        ),
        migrations.AlterField(
            model_name="order",
            name="contact",
            field=models.CharField(max_length=64, verbose_name="Контактные данные"),
        ),
    ]
