# Generated by Django 4.2.4 on 2023-10-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0006_alter_order_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, verbose_name="Итого"
            ),
        ),
    ]
